import {
  convertWithMarkitdown,
  fileExists,
  fileModifiedMs,
  readFile,
  writeFile,
} from "@/commands/fs"
import { getFileName, normalizePath } from "@/lib/path-utils"

export type SourceConversionMethod =
  | "converted-cache"
  | "markitdown"
  | "native"

export interface LoadedSourceForIngest {
  content: string
  method: SourceConversionMethod
  convertedPath?: string
  error?: string
}

const DIRECT_TEXT_EXTENSIONS = new Set(["md", "markdown", "txt"])

function trimTrailingSlash(path: string): string {
  return normalizePath(path).replace(/\/+$/, "")
}

function extensionOf(path: string): string {
  const name = getFileName(path)
  const dot = name.lastIndexOf(".")
  return dot >= 0 ? name.slice(dot + 1).toLowerCase() : ""
}

export function rawSourcesRelativePath(
  projectPath: string,
  sourcePath: string,
): string | null {
  const project = trimTrailingSlash(projectPath)
  const source = normalizePath(sourcePath)
  const root = `${project}/raw/sources`
  if (!source.startsWith(`${root}/`)) return null

  const relative = source.slice(root.length + 1)
  const parts = relative.split("/")
  if (
    parts.length === 0 ||
    parts.some((part) => !part || part === "." || part === "..") ||
    parts[0] === ".cache"
  ) {
    return null
  }

  return parts.join("/")
}

export function convertedMarkdownPath(
  projectPath: string,
  sourcePath: string,
): string | null {
  const relative = rawSourcesRelativePath(projectPath, sourcePath)
  if (!relative) return null
  return `${trimTrailingSlash(projectPath)}/.llm-wiki/converted/${relative}.md`
}

async function isConvertedCacheFresh(
  sourcePath: string,
  convertedPath: string,
): Promise<boolean> {
  try {
    if (!(await fileExists(convertedPath))) return false
    const [sourceMtime, convertedMtime] = await Promise.all([
      fileModifiedMs(sourcePath),
      fileModifiedMs(convertedPath),
    ])
    return sourceMtime !== null &&
      convertedMtime !== null &&
      convertedMtime >= sourceMtime
  } catch {
    return false
  }
}

export async function loadSourceForIngest(
  projectPath: string,
  sourcePath: string,
): Promise<LoadedSourceForIngest> {
  const normalizedSource = normalizePath(sourcePath)
  const convertedPath = convertedMarkdownPath(projectPath, normalizedSource)
  if (!convertedPath || DIRECT_TEXT_EXTENSIONS.has(extensionOf(normalizedSource))) {
    return {
      content: await readFile(normalizedSource),
      method: "native",
    }
  }

  if (await isConvertedCacheFresh(normalizedSource, convertedPath)) {
    return {
      content: await readFile(convertedPath),
      method: "converted-cache",
      convertedPath,
    }
  }

  try {
    const result = await convertWithMarkitdown(normalizedSource)
    const markdown = result.markdown?.trimEnd()
    if (result.ok && markdown) {
      const content = `${markdown}\n`
      await writeFile(convertedPath, content)
      return {
        content,
        method: "markitdown",
        convertedPath,
      }
    }

    const nativeContent = await readFile(normalizedSource)
    return {
      content: nativeContent,
      method: "native",
      convertedPath,
      error: result.error ?? "MarkItDown did not return markdown",
    }
  } catch (error) {
    return {
      content: await readFile(normalizedSource),
      method: "native",
      convertedPath,
      error: error instanceof Error ? error.message : String(error),
    }
  }
}

export async function deleteConvertedSourceCache(
  projectPath: string,
  sourcePath: string,
): Promise<void> {
  const path = convertedMarkdownPath(projectPath, sourcePath)
  if (!path) return
  try {
    const { deleteFile } = await import("@/commands/fs")
    await deleteFile(path)
  } catch {
    // Non-critical: converted Markdown is a cache and stale entries
    // are ignored/regenerated by mtime checks on future ingest.
  }
}
